# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.4.1

test_defaults:
  before_init: ["terraform init && terraform test"]

# The set of tests to run to verify your module works correctly
tests:
  - name: Test the module with terraform 1.5.7
    terraform_version: 1.5.7
    environment:
      TF_VAR_bacon: con
  - name: Test the module with terraform 1.4.7
    terraform_version: 1.4.7
    environment:
      TF_VAR_bacon: acon
  - name: Test the module with terraform 1.3.10
    terraform_version: 1.3.10
    environment:
      TF_VAR_bacon: bacon